### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by BernardPinard** [pkmn/POSHO-9000#1]
Hey ! I have this problem : 

C:\POSHO-9000-master>npm start

> @ start C:\POSHO-9000-master
> npm run compile && node build/index config.json

> @ compile C:\POSHO-9000-master
> tsc -p .

Connected to Showdown server

C:\POSHO-9000-master\index.ts:197
    for (const [roomid, battle] of Object.entries(rooms)) {
                                          ^
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Client.onQueryresponse (C:\POSHO-9000-master\index.ts:197:43)
    at Client.onMessage (C:\POSHO-9000-master\index.ts:160:12)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (C:\POSHO-9000-master\node_modules\websocket\lib\WebSocketConnection.js:554:26)
    at C:\POSHO-9000-master\node_modules\websocket\lib\WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `npm run compile && node build/index config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bernard\AppData\Roaming\npm-cache\_logs\2021-03-07T12_21_25_367Z-debug.log

C:\POSHO-9000-master>

**Comment by scheibo** [comment]
Thanks, I noticed this issue when I was setting up the bot for the LC room recently and didn't bother pushing the fix.
